# Generated by Django 3.1.7 on 2021-03-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='single_use',
            field=models.BooleanField(default=True),
        ),
    ]
