# Generated by Django 3.1.7 on 2021-03-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210319_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/no_image.png', upload_to='products/%Y/%m/%d'),
        ),
    ]
