# Generated by Django 3.1.7 on 2021-04-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210405_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_physical',
            field=models.BooleanField(default=True),
        ),
    ]
