# Generated by Django 3.1.7 on 2021-04-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_is_physical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
