# Generated by Django 3.1.7 on 2021-04-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210406_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mailing_address',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='r', max_length=12),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MailingAddress',
        ),
    ]
